// ---------------------------------------------------------------------------
// Surya Enterprises — company / business profile content.
//
// ONE source for everything the About page (app/aboutUs/page.jsx) and the
// downloadable Business Profile PDF (scripts/build-company-profile.mjs) say
// about the business. Edit here and both update on the next build.
//
// Facts only. Figures the business has not supplied (revenue, farmer counts,
// licence numbers) are deliberately absent — see the `null` / empty slots
// below and `SITE.licences` in site.js. Contact, office, GSTIN, certification
// and grievance-officer details are read from site.js so they are never
// duplicated. Catalogue figures come from app/products/data/catalog-facts.js,
// which the catalogue import regenerates, so they are always the live numbers.
// ---------------------------------------------------------------------------
// Explicit ".js" so Node can import this module directly from scripts/.
import { SITE } from "./site.js";
import { CATALOG_FACTS as FACTS } from "../products/data/catalog-facts.js";

const FOUNDED = 2023;
const fmt = (n) => n.toLocaleString("en-IN");

// Brands named in the positioning line. Every one is verified against the
// catalogue by the PDF build script.
const EXAMPLE_BRANDS = ["Syngenta", "Namdhari Seeds", "East West", "Bayer", "Dhanuka", "KisanKraft"];
const brandList = `${EXAMPLE_BRANDS.slice(0, -1).join(", ")} and ${EXAMPLE_BRANDS.at(-1)}`;
const CATEGORY_LIST = "seeds, crop protection, crop nutrition, farm machinery and animal husbandry";

export const COMPANY_PROFILE = {
  founded: FOUNDED,

  name: "Surya Enterprises",
  tradeName: "Surya Enterprises",
  displayName: "SURYA ENTERPRISES",
  legalName: SITE.legalName,
  tagline: "India's agriculture marketplace",
  positioning: "India's agriculture marketplace, built from inside the supply chain.",
  website: { display: "www.suryaenter.in", url: "https://www.suryaenter.in" },

  // One-line nature of business (identity block of the PDF).
  natureOfBusiness:
    "Licensed agri-inputs marketplace offering leading brands alongside Surya Enterprises' own crop-protection range",

  // The generated PDF (public/downloads). `pages` is asserted by the build script.
  pdf: {
    href: "/downloads/surya-enterprises-company-profile.pdf",
    title: "Business Profile",
    subtitle: "Nature of business declaration",
    pages: 3,
    format: "A4",
    caption: "nature of business, products, channels, customers",
    linkLabel: "Business profile (PDF)",
    buttonLabel: "Download business profile (PDF)",
  },

  // Hero chips on the About page.
  coverChips: [`Founded ${FOUNDED}`, "Licensed agri-inputs marketplace", "ISO & ZED certified"],

  // Live catalogue facts (regenerated by scripts/import-brand-catalog.mjs).
  catalogue: {
    products: FACTS.products,
    skus: FACTS.skus,
    brands: FACTS.brands,
    priceMin: FACTS.priceMin,
    priceMax: FACTS.priceMax,
    categories: FACTS.categories.map((c) => c.name),
    exampleBrands: EXAMPLE_BRANDS,
    importDate: FACTS.importDate,
  },

  // Share of sales by customer type (percent).
  salesMix: { b2c: 70, b2b: 30 },

  // Unknown figures — intentionally null so nothing is invented. Fill when the
  // business supplies audited numbers and extend the page/PDF to render them.
  revenue: null,
  farmersServed: null,

  // ---- PDF section 1: nature of business ------------------------------------
  nature: {
    paragraph:
      `${SITE.legalName}, trading as Surya Enterprises, is a licensed agri-inputs marketplace based at Rajdhani Krishi Mandi, Jaipur, with a corporate office in New Delhi. It sells ${CATEGORY_LIST} products from leading brands (${brandList}) alongside its own crop-protection range, directly to farmers and institutional buyers through its website, its Jaipur store and an institutional desk. Founded in ${FOUNDED} as a backend support channel for the agri-inputs supply chain, the company was incorporated to build the Surya Marketplace.`,
    bullets: [
      "Licensed agri-inputs marketplace: genuine products from leading brands alongside Surya's own crop-protection range (ISO and ZED certified; marked “Manufacturer direct” online).",
      "Sells directly to farmers (B2C, 70% of sales) and to universities and institutes, bulk enterprises, dealers and co-operatives (B2B, 30%).",
      // {priceRange} is filled by the build script with ₹ (brand fonts embedded) or "INR".
      `Online catalogue: ${fmt(FACTS.products)} products, ${fmt(FACTS.skus)} pack sizes, ${fmt(FACTS.brands)} brands across ${CATEGORY_LIST}, priced {priceRange} per pack.`,
      "Bulk quantities, technical grades and custom packaging by quotation through the institutional desk; every online product is also sold at the Jaipur store.",
    ],
  },

  // ---- About page: "Where we started" ------------------------------------
  origin: {
    eyebrow: "Where we started",
    title: "Three years inside the supply chain",
    paragraphs: [
      `Surya Enterprises began in ${FOUNDED} as a backend support channel for the agriculture-products supply chain — the operations layer that keeps inputs moving from manufacturers to the distributors, wholesalers and retailers who sell to farmers.`,
      "Working inside that chain, the founders watched the same pattern repeat at every hand-off: each layer added its margin, stock went missing exactly when crops needed it, and the farmer at the end paid the most while knowing the least about what was in the pack.",
      "So the company was incorporated as SURYA ENTERPRISES and built the Surya Marketplace — a licensed channel that sells leading brands and Surya's own range to farmers and institutions without the layers in between.",
    ],
    milestones: [
      { when: String(FOUNDED), title: "Backend support channel", text: "Operations support for the agri-inputs supply chain." },
      { when: "Inside the chain", title: "The problem, first-hand", text: "Layered margins, stock-outs and counterfeit packs seen at every hand-off." },
      { when: "Today", title: "SURYA ENTERPRISES", text: "Incorporated; the Surya Marketplace sells leading brands and Surya's own range direct to farmers and institutions." },
    ],
  },

  // ---- About page: "The problem we saw" ------------------------------------
  problem: {
    eyebrow: "The problem we saw",
    title: "The farmer pays the most and knows the least",
    intro:
      "A ₹500–₹1,000 pack of crop protection passes through several hands before it reaches a field in a district like Sikar. Each hand takes a margin; none of them owes the farmer an explanation.",
    // The conventional route of a pack from factory to field.
    chain: ["Manufacturer", "Distributor", "Wholesaler", "Retailer", "Commission agent", "Farmer"],
    cards: [
      {
        icon: "layers",
        title: "Layered margins",
        text: "Distributor, wholesaler, retailer and commission agent each add a margin on the way to the field. Small and marginal farmers — buying one pack at a time — end up paying the highest price for it.",
      },
      {
        icon: "calendar",
        title: "Stock-outs at sowing and spraying time",
        text: "Inputs are needed in short windows: sowing, and the days when a pest or disease first shows. When the local shop is out of stock in that window, the crop pays for it.",
      },
      {
        icon: "alert",
        title: "Counterfeit and adulterated inputs",
        text: "With no transparent origin, a farmer cannot tell a genuine pack from a counterfeit or adulterated one — until the spray does not work.",
      },
      {
        icon: "eyeoff",
        title: "No guidance, no price transparency",
        text: "The farmer paying the most gets the least: no technical guidance on what to use, and no way to see what the product should actually cost.",
      },
    ],
  },

  // ---- About page: "Our answer" ---------------------------------------------
  answer: {
    eyebrow: "Our answer",
    title: "The Surya Marketplace",
    intro:
      "A licensed marketplace that delivers agri-inputs directly to farmers. It removes the middlemen and the commissions they add, so the farmer's money goes into the product.",
    quote: "The farmer's money goes into the product — and the farmer relies on us.",
    chain: ["Surya Enterprises", "Farmer"],
    points: [
      {
        icon: "truck",
        title: "Direct to the farmer",
        text: "Orders on the website or at our store go from Surya Enterprises to the farmer. No distributor, wholesaler or commission agent in between.",
      },
      {
        icon: "label",
        title: "Licensed to sell agro-inputs",
        text: "Surya Enterprises is licensed to sell agro-inputs in India, and every listing shows the brand, category, pack size and SKU.",
      },
      {
        icon: "factory",
        title: "Leading brands and our own range",
        text: `Genuine packs from ${brandList} and other leading brands, alongside Surya Enterprises' own crop-protection range — ISO and ZED (Zero Defect Zero Effect) certified and marked “Manufacturer direct”.`,
      },
      {
        icon: "sprout",
        title: "What changes for a farmer",
        text: `A listed price before buying, stock shown before ordering, sealed manufacturer packs, and a helpline (${SITE.helpline.hours}) for product questions.`,
      },
    ],
  },

  // ---- Product portfolio ------------------------------------------------------
  // All five lines are live on the website (categorySlug → /c/<slug>).
  // Example product names are verified against products.json by the build script.
  productLines: [
    {
      name: "Seeds",
      detail: "Vegetable, fruit, flower, field and forage seeds",
      icon: "wheat",
      online: true,
      categorySlug: "seeds",
      examples: ["Syngenta OH-102 Okra (Bhendi) Seeds", "Namdhari NS 22 Cabbage Seeds", "RUDRA CHILLI", "Abhilash Tomato Seeds"],
    },
    {
      name: "Crop protection",
      detail: "Insecticides, fungicides, herbicides, bio-controls, traps and lures",
      icon: "bug",
      online: true,
      categorySlug: "crop-protection",
      examples: ["Confidor Insecticide", "Cuman L Fungicide", "Dhanuka Barrier Herbicide (Metribuzin 70% WP)", "Applaud Insecticide (Buprofezin 25% SC)"],
    },
    {
      name: "Crop nutrition",
      detail: "Fertilisers, bio-fertilisers, biostimulants and growth regulators",
      icon: "sack",
      online: true,
      categorySlug: "crop-nutrition",
      examples: ["IFFCO Nano Urea Plus Fertilizers", "Rallis Surplus Micronutrient Fertilizer", "Allborich Liquid Micronutrient Fertilizer", "IFFCO Humetsu Humic Acid"],
    },
    {
      name: "Farm machinery",
      detail: "Sprayers, brush cutters, tillers, hand tools, tarpaulins and mulches",
      icon: "tools",
      online: true,
      categorySlug: "farm-machinery",
      examples: ["AMH16 HITECH KNAPSACK SPRAYER", "Anil Packaging HDPE Tarpaulin 250 GSM", "MANUAL SEEDER KK MSD S01", "Mipatex Tree Weed Mat"],
    },
    {
      name: "Animal husbandry",
      detail: "Cattle feed, milking equipment, poultry and fish care",
      icon: "cattle",
      online: true,
      categorySlug: "animal-husbandry",
      examples: ["GODHAN GS 120 MILKING MACHINE", "Century Biocare Rumistar", "MEENAKSHI CHICK DRINKER", "ECOWEALTH SILAGE CULTURE"],
    },
  ],
  availability: {
    online: { badge: "Online now", channels: "Website + store" },
    offline: {
      badge: "By quotation",
      channels: "Institutional desk",
      note: "Bulk quantities, technical grades and custom packaging are supplied by quotation; every online product can also be bought at the Jaipur store.",
    },
  },

  // ---- Sales channels -----------------------------------------------------------
  // `how` / `payment` feed the PDF channel table; the rest feeds the About cards.
  channels: [
    {
      key: "website",
      icon: "globe",
      title: "Website",
      detail: "www.suryaenter.in",
      text: "Browse by category, brand, crop and pack size. Pay by UPI via PayU; dispatch to serviceable PIN codes across India.",
      how: "Online orders at www.suryaenter.in (browse by category, brand, crop and pack size); dispatched to serviceable PIN codes across India.",
      payment: SITE.payments.join(", "),
      href: "/products",
      cta: "Shop online",
    },
    {
      key: "store",
      icon: "store",
      title: "In-store",
      detail: "Rajdhani Krishi Mandi, Jaipur",
      text: "Buy in person at our registered office in Jaipur's agricultural mandi.",
      how: `Walk-in purchases at the registered office: ${SITE.offices[0].address} (${SITE.helpline.hours}).`,
      payment: "At the store counter",
      href: "/contact",
      cta: "Contact & directions",
    },
    {
      key: "institutional",
      icon: "building",
      title: "Institutional desk",
      detail: "Quotations · GST invoice",
      text: "Bulk supply and technical grades with listed purity for universities, institutes, bulk enterprises, dealers and co-operatives.",
      how: `Quotations by phone (${SITE.helpline.display}) or email (${SITE.email}); GST invoice issued for every supply.`,
      payment: `Bank transfer / UPI. ${SITE.policies.bulk.creditTerms}`,
      href: "/products/institutional",
      cta: "Request a quotation",
    },
  ],

  // ---- Customer segments ----------------------------------------------------------
  segments: [
    {
      key: "b2c",
      share: 70,
      label: "B2C",
      title: "Farmers",
      text: "Farmers buying for their own fields, per pack — on the website or in-store.",
      who: ["Small and marginal farmers", "Individual growers"],
    },
    {
      key: "b2b",
      share: 30,
      label: "B2B",
      title: "Institutions & bulk buyers",
      text: "Buying by quotation through the institutional desk, with GST invoices.",
      who: ["Agricultural universities and institutes", "Bulk enterprises", "Dealers and co-operatives"],
    },
  ],

  paymentPartners: ["PayU", "Razorpay"],
  // Agro-input sales licences — rendered only when SITE.licences is filled.
  licences: SITE.licences ?? [],
  licencesFallback: "Licence details available on request.",

  // ---- PDF section 6: declaration ---------------------------------------------------
  declaration: {
    statement: "We confirm that the information above is true and describes the current nature of our business.",
    signatureFields: ["Name", "Designation", "Date", "Signature / Stamp"],
  },
};

// Price range as text. `currency` is "₹" on the web; the PDF uses "INR "
// because pdfkit's built-in Helvetica (WinAnsi) has no rupee glyph.
export function priceRange(currency = "₹", p = COMPANY_PROFILE) {
  return `${currency}${fmt(p.catalogue.priceMin)} – ${currency}${fmt(p.catalogue.priceMax)}`;
}

// Social-selling statement for the PDF, driven by SITE.social: as long as no
// profile URL is configured the business declares no social / third-party
// marketplace sales; once profiles are set the sentence names them.
export function socialStatement() {
  const names = { facebook: "Facebook", instagram: "Instagram", youtube: "YouTube", linkedin: "LinkedIn", x: "X (Twitter)" };
  const active = Object.entries(SITE.social ?? {})
    .filter(([, url]) => Boolean(url))
    .map(([key]) => names[key] ?? key);
  if (active.length === 0) return "No sales through social media or third-party marketplaces at present.";
  return `Social media presence: ${active.join(", ")} (brand communication only). Sales are made through the channels above; no sales through third-party marketplaces.`;
}

// "7 October 2026" from an ISO date (or a Date).
export function formatProfileDate(d) {
  const date = d instanceof Date ? d : new Date(`${d}T00:00:00`);
  return date.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
}
